"""
Interactive, tamper-resistant remediation lessons (public endpoints).

Flow: an employee who clicked a simulated phish reaches the awareness-reveal
page, which links here. They pick a medium (watch / listen) and a language
(English / Nepali), then complete the lesson. Playback is verified server-side:

    browser reports playback  ->  backend validates  ->  backend decides

The backend never trusts ``currentTime == duration``. It maintains a UNION of
verified watch segments built from heartbeats, so seeking to the end counts as
nothing, tab-switches pause verified time, and only one playback session per
attempt can contribute time at a time. Completion additionally requires every
interactive checkpoint answered correctly and a quiz score >= pass_score.
"""

import json
import uuid
from datetime import datetime, timezone
from pathlib import Path

from fastapi import APIRouter, Depends
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from .core.config import get_settings
from .database import get_public_db
from .models import (
    Campaign, CampaignResult, EventType, PhishingEvent, PlaybackEvent,
    TrainingAttempt, TrainingModule, TrainingQuestion, TrainingStatus,
)

router = APIRouter(prefix="/track", tags=["training"])

# Verified segments are only accepted when playback advances by no more than
# server-elapsed time + this allowance (seconds). Anything bigger is a seek.
SEEK_ALLOWANCE_SECONDS = 6.0
# A new browser window may only take over the active session after this many
# seconds of silence from the previous one.
SESSION_CLAIM_TTL_SECONDS = 60.0
COMPLETION_COVERAGE = 0.95  # >= 95% verified coverage required

# Lesson media. Each lesson has a topic-specific training video generated by
# scripts/generate_training_videos.py (slides + voiceover, English and Nepali),
# served locally by the backend from /media. Research on security-awareness
# microlearning consistently lands on ~2-5 minutes per module (systematic
# reviews cite 1-3 / 5-7 / 5-8 minute formats as equally effective, and
# industry phishing curricula standardize around 5 minutes) — and these
# videos are delivered just-in-time, right after an employee clicks a phish,
# so 2.5-3 minutes keeps the lesson finishable at the moment of need.
MEDIA_BASE = "/media/training/"
FAILURE_TO_VIDEO = {
    "phishing-basics": "phishing-basics",
    "credential-phishing": "credential-phishing",
    "malware-link": "malware-link",
    "urgency-bait": "urgency-bait",
}


def _media_url(failure_type: str, lang: str) -> str:
    return f"{MEDIA_BASE}{FAILURE_TO_VIDEO.get(failure_type, 'phishing-basics')}_{lang}.mp4"


def media_absolute_url(url: str | None) -> str | None:
    """Turn a stored relative /media/... URL into an absolute one so browser
    <video> tags resolve it against the API origin. Absolute URLs (legacy demo
    media, external hosts) pass through untouched."""
    if not url or not str(url).startswith("/media/"):
        return url
    base = get_settings().API_BASE_URL.rstrip("/")
    return f"{base}{url}"


# URLs seeded by earlier versions (random demo movies or legacy samples) that
# were unrelated to the lesson topic; they are swapped onto the topic video.
LEGACY_VIDEO_URLS = {
    "https://archive.org/download/Sintel/sintel-2048-stereo_512kb.mp4",
    "https://archive.org/download/ElephantsDream/ed_1024_512kb.mp4",
    "https://archive.org/download/spring_blenderopenmovie/Spring%20-%20Blender%20Open%20Movie%20-%20YouTube.mp4",
    "https://archive.org/download/tears-of-steel_202504/Tears%20of%20Steel.mp4",
    "https://archive.org/download/cosmos-laundromat/Cosmos%20Laundromat.mp4",
    "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
    "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/friday.mp4",
    "https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-mp4-file.mp4",
    "https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/360/Big_Buck_Bunny_360_10s_1MB.mp4",
    "https://test-videos.co.uk/vids/sintel/mp4/h264/360/Sintel_360_10s_1MB.mp4",
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
}

# Minimum lesson length. The generated lesson videos run 2.3-3.1 minutes; the
# client reports the real media duration and verified watch time must cover
# 95% of it, so this floor only guards against future regressions.
MIN_LESSON_SECONDS = 130  # ~2 minutes 10 seconds

_DURATIONS_CACHE: dict | None = None


def lesson_duration_seconds(failure_type: str, lang: str) -> float:
    """True media length from durations.json (written by the video generator).
    Falls back to MIN_LESSON_SECONDS when the manifest is unavailable."""
    global _DURATIONS_CACHE
    if _DURATIONS_CACHE is None:
        manifest = Path(__file__).resolve().parent.parent / "media" / "training" / "durations.json"
        try:
            _DURATIONS_CACHE = json.loads(manifest.read_text())
        except (OSError, ValueError):
            _DURATIONS_CACHE = {}
    return float(
        (_DURATIONS_CACHE.get(failure_type) or {}).get(lang, MIN_LESSON_SECONDS)
    )

# Map a campaign's template category to the failure type it is teaching about.
CATEGORY_TO_FAILURE = {key.lower(): value for key, value in {
    "Finance": "credential-phishing",
    "Internal IT": "credential-phishing",
    "Collaboration": "malware-link",
    "HR": "urgency-bait",
    "Delivery": "urgency-bait",
}.items()}
FALLBACK_FAILURE = "phishing-basics"


# ── Verified-time helpers ───────────────────────────────────────────────────

def _as_utc(dt) -> datetime:
    """SQLite returns offset-naive datetimes; normalize to aware UTC."""
    if dt is None:
        return datetime.now(timezone.utc)
    if dt.tzinfo is None:
        return dt.replace(tzinfo=timezone.utc)
    return dt.astimezone(timezone.utc)


def _merge_segments(segments: list, start: float, end: float) -> list:
    """Add [start, end] to a list of verified [start, end] segments and return
    the normalized (merged) union. Segments that don't overlap the new window
    (entirely before or after it) are kept as-is; the rest are unioned."""
    if start is None or end is None or end <= start or start < 0:
        return segments or []
    merged = [seg for seg in (segments or []) if seg[1] <= start or seg[0] >= end]
    merged.append([start, end])
    merged.sort(key=lambda pair: pair[0])
    out = []
    for lo, hi in merged:
        if out and lo <= out[-1][1]:
            out[-1][1] = max(out[-1][1], hi)
        else:
            out.append([lo, hi])
    return out


def _union_length(segments: list) -> float:
    return sum(hi - lo for lo, hi in segments)


def _append_flag(attempt: TrainingAttempt, flag: str) -> None:
    flags = list(attempt.invalid_flags or [])
    if flag not in flags:
        flags.append(flag)
        attempt.invalid_flags = flags


# ── Shared helpers ──────────────────────────────────────────────────────────

async def _resolve_result(token: str, db: AsyncSession) -> tuple[CampaignResult | None, Campaign | None]:
    try:
        token_uuid = uuid.UUID(str(token))
    except (ValueError, AttributeError, TypeError):
        return None, None
    result = await db.scalar(select(CampaignResult).where(CampaignResult.tracking_token == token_uuid))
    if result is None:
        return None, None
    campaign = await db.scalar(select(Campaign).where(Campaign.id == result.campaign_id))
    return result, campaign


async def _pick_module(db: AsyncSession, org_id, campaign: Campaign | None) -> TrainingModule | None:
    failure = FALLBACK_FAILURE
    if campaign is not None:
        from .models import PhishingTemplate  # local import to avoid circulars

        template = await db.get(PhishingTemplate, campaign.template_id)
        failure = CATEGORY_TO_FAILURE.get((template.category or "").strip().lower(), FALLBACK_FAILURE)

    stmt = select(TrainingModule).where(
        TrainingModule.failure_type == failure,
        TrainingModule.is_active == True,  # noqa: E712
        (TrainingModule.org_id.is_(None)) | (TrainingModule.org_id == org_id),
    ).order_by(TrainingModule.org_id.is_(None), TrainingModule.version.desc())
    module = (await db.execute(stmt)).scalars().first()
    if module is None and failure != FALLBACK_FAILURE:
        stmt = select(TrainingModule).where(
            TrainingModule.failure_type == FALLBACK_FAILURE,
            TrainingModule.is_active == True,  # noqa: E712
            (TrainingModule.org_id.is_(None)) | (TrainingModule.org_id == org_id),
        ).order_by(TrainingModule.org_id.is_(None), TrainingModule.version.desc())
        module = (await db.execute(stmt)).scalars().first()
    if module is None:
        module = (await db.execute(
            select(TrainingModule).where(
                TrainingModule.is_active == True,  # noqa: E712
                (TrainingModule.org_id.is_(None)) | (TrainingModule.org_id == org_id),
            ).order_by(TrainingModule.org_id.is_(None))
        )).scalars().first()
    return module


async def _load_questions(db: AsyncSession, module_id) -> list[TrainingQuestion]:
    return (await db.execute(
        select(TrainingQuestion).where(TrainingQuestion.module_id == module_id)
    )).scalars().all()


def _public_question(q: TrainingQuestion) -> dict:
    """Question payload with NO answer key — the server validates answers."""
    return {
        "id": q.id,
        "prompt": q.prompt,
        "prompt_ne": q.prompt_ne,
        "options": q.options,
        "checkpoint_after_seconds": q.checkpoint_after_seconds,
    }


def _session_ok(attempt: TrainingAttempt, session: str, now: datetime) -> bool:
    """Single-active-session check. Returns True if this session may write."""
    if not attempt.session_id or attempt.session_id == session:
        return True
    last = _as_utc(attempt.last_activity_at)
    if last is None or (now - last).total_seconds() >= SESSION_CLAIM_TTL_SECONDS:
        attempt.session_id = session  # stale session expired — claim the tab
        return True
    return False


def _coverage(attempt: TrainingAttempt, module: TrainingModule) -> tuple[float, float]:
    duration = attempt.video_duration or module.duration_seconds or 1
    verified = _union_length(attempt.watch_segments or [])
    coverage = min(100.0, round(verified / duration * 100, 1)) if duration else 0.0
    return verified, coverage


# ── Endpoints ───────────────────────────────────────────────────────────────

@router.get("/training/start")
async def training_start(
    token: str,
    lang: str = "en",
    mode: str = "watch",
    session: str = "",
    db: AsyncSession = Depends(get_public_db),
):
    result, campaign = await _resolve_result(token, db)
    if result is None:
        return {"ok": False, "error": "Unknown training link"}

    lang = lang if lang in ("en", "ne") else "en"
    mode = mode if mode in ("watch", "listen") else "watch"
    org_id = campaign.org_id if campaign is not None else None
    module = await _pick_module(db, org_id, campaign)
    if module is None:
        return {"ok": False, "error": "No lesson configured yet"}

    questions = await _load_questions(db, module.id)

    # Already trained via the legacy micro-lesson flow? Return a read-only summary.
    if result.training_completed:
        return {
            "ok": True,
            "already_trained": True,
            "status": "completed",
            "module": _module_payload(module, lang, mode),
            "questions": [_public_question(q) for q in questions],
        }

    attempt = (
        await db.execute(
            select(TrainingAttempt).where(
                TrainingAttempt.result_id == result.id,
                TrainingAttempt.module_id == module.id,
                TrainingAttempt.status.in_(
                    [TrainingStatus.STARTED, TrainingStatus.IN_PROGRESS, TrainingStatus.QUIZ_REQUIRED]
                ),
            ).order_by(TrainingAttempt.started_at.desc())
        )
    ).scalars().first()

    now = datetime.now(timezone.utc)
    if attempt is None:
        attempt = TrainingAttempt(
            org_id=org_id,
            employee_id=result.employee_id,
            module_id=module.id,
            campaign_id=result.campaign_id,
            result_id=result.id,
            language=lang,
            mode=mode,
            status=TrainingStatus.STARTED,
            session_id=session or str(uuid.uuid4()),
            last_activity_at=now,
        )
        db.add(attempt)
    else:
        attempt.language = lang
        attempt.mode = mode
        attempt.session_id = session or attempt.session_id or str(uuid.uuid4())
        attempt.last_activity_at = now
    await db.commit()
    await db.refresh(attempt)

    verified, coverage = _coverage(attempt, module)
    checkpoints = []
    checkpoint_questions = [q for q in questions if q.checkpoint_after_seconds is not None]
    passed_ids = {str(c["question_id"]) for c in (attempt.checkpoints or []) if c.get("passed")}
    for q in checkpoint_questions:
        checkpoints.append({
            "question_id": str(q.id),
            "passed": str(q.id) in passed_ids,
            "checkpoint_after_seconds": q.checkpoint_after_seconds,
        })

    return {
        "ok": True,
        "attempt_id": attempt.id,
        "status": attempt.status.value,
        "language": lang,
        "mode": mode,
        "module": _module_payload(module, lang, mode),
        "questions": [_public_question(q) for q in questions],
        "checkpoints": checkpoints,
        "verified_watch_seconds": round(verified, 1),
        "completion_percentage": coverage,
        "video_duration": attempt.video_duration,
        "quiz_score": attempt.quiz_score,
        "quiz_passed": attempt.quiz_passed,
        "invalid_flags": attempt.invalid_flags or [],
    }


def _module_payload(module: TrainingModule, lang: str, mode: str) -> dict:
    is_ne = lang == "ne"
    if mode == "listen":
        url = module.audio_url_ne or module.video_url_ne if is_ne else module.audio_url_en or module.video_url_en
    else:
        url = module.video_url_ne if is_ne else module.video_url_en
    return {
        "id": module.id,
        "title": module.title_ne if is_ne else module.title,
        "description": module.description_ne if is_ne else module.description,
        "failure_type": module.failure_type,
        "language": lang,
        "mode": mode,
        "media_url": media_absolute_url(url),
        "duration_seconds": module.duration_seconds,
        "pass_score": module.pass_score,
        "key_points": module.key_points_ne if is_ne else module.key_points_en,
    }


async def _get_attempt(db: AsyncSession, attempt_id) -> TrainingAttempt | None:
    try:
        return await db.get(TrainingAttempt, uuid.UUID(str(attempt_id)))
    except (ValueError, AttributeError, TypeError):
        return None


def _progress_into(attempt: TrainingAttempt, questions: list[TrainingQuestion]) -> None:
    """Move the state machine forward based on verified coverage + checkpoints."""
    checkpoint_ids = {str(q.id) for q in questions if q.checkpoint_after_seconds is not None}
    done = {str(c["question_id"]) for c in (attempt.checkpoints or []) if c.get("passed")}
    if checkpoint_ids and not checkpoint_ids.issubset(done):
        attempt.status = TrainingStatus.IN_PROGRESS
    elif attempt.completion_percentage < COMPLETION_COVERAGE * 100:
        attempt.status = TrainingStatus.IN_PROGRESS
    else:
        attempt.status = TrainingStatus.QUIZ_REQUIRED


@router.post("/training/heartbeat")
async def training_heartbeat(payload: dict, db: AsyncSession = Depends(get_public_db)):
    attempt = await _get_attempt(db, payload.get("attempt_id"))
    if attempt is None:
        return {"ok": False, "error": "Attempt not found"}
    if attempt.status == TrainingStatus.COMPLETED:
        module = await db.get(TrainingModule, attempt.module_id)
        return {
            "ok": True, "completed": True, "status": attempt.status.value,
            "completion_percentage": attempt.completion_percentage,
        }

    now = datetime.now(timezone.utc)
    if not _session_ok(attempt, str(payload.get("session") or ""), now):
        return {"ok": False, "code": "inactive_session", "message": "This lesson is playing in another window."}

    position = float(payload.get("position") or 0.0)
    playing = bool(payload.get("playing"))
    hidden = bool(payload.get("hidden"))
    media_duration = payload.get("media_duration")
    speed = payload.get("speed")

    if media_duration and not attempt.video_duration:
        attempt.video_duration = float(media_duration)

    elapsed = 0.0
    if attempt.last_activity_at is not None:
        elapsed = (now - _as_utc(attempt.last_activity_at)).total_seconds()
    prev = attempt.last_position or 0.0
    delta = position - prev

    if speed is not None and float(speed) > 1.0:
        _append_flag(attempt, "speed-change")

    if playing and not hidden:
        if 0.0 <= delta <= elapsed + SEEK_ALLOWANCE_SECONDS:
            segments = _merge_segments(attempt.watch_segments, prev, position)
            attempt.watch_segments = segments
            event_type = "heartbeat"
        elif delta > elapsed + SEEK_ALLOWANCE_SECONDS:
            _append_flag(attempt, "seek-forward")
            event_type = "seek"
        else:
            _append_flag(attempt, "seek-back")
            event_type = "seek"
        attempt.last_position = position
    elif playing and hidden:
        _append_flag(attempt, "tab-hidden")
        attempt.last_position = position
        event_type = "tab-hidden"
    else:
        attempt.last_position = position
        event_type = "paused"

    verified, coverage = _coverage(attempt, await db.get(TrainingModule, attempt.module_id))
    attempt.verified_watch_seconds = round(verified, 1)
    attempt.completion_percentage = coverage
    attempt.last_activity_at = now
    if attempt.status == TrainingStatus.STARTED:
        attempt.status = TrainingStatus.IN_PROGRESS

    db.add(PlaybackEvent(
        attempt_id=attempt.id,
        event_type=event_type,
        position=position,
        client_ts=payload.get("client_ts"),
        event_data={"playing": playing, "hidden": hidden},
    ))
    await db.commit()

    return {
        "ok": True,
        "verified_watch_seconds": attempt.verified_watch_seconds,
        "completion_percentage": coverage,
        "status": attempt.status.value,
        "invalid_flags": attempt.invalid_flags or [],
    }


@router.post("/training/checkpoint")
async def training_checkpoint(payload: dict, db: AsyncSession = Depends(get_public_db)):
    attempt = await _get_attempt(db, payload.get("attempt_id"))
    if attempt is None:
        return {"ok": False, "error": "Attempt not found"}
    if not _session_ok(attempt, str(payload.get("session") or ""), datetime.now(timezone.utc)):
        return {"ok": False, "code": "inactive_session", "message": "This lesson is playing in another window."}

    question = await db.get(TrainingQuestion, uuid.UUID(str(payload.get("question_id"))))
    if question is None or question.module_id != attempt.module_id:
        return {"ok": False, "error": "Unknown question"}
    if question.checkpoint_after_seconds is None:
        return {"ok": False, "error": "This is a quiz question, not a checkpoint"}

    answer = int(payload.get("answer_index", -1))
    correct = answer == question.correct_index

    checkpoints = [dict(c) for c in (attempt.checkpoints or [])]
    entry = next((c for c in checkpoints if str(c["question_id"]) == str(question.id)), None)
    if entry is None:
        entry = {"question_id": str(question.id), "passed": False, "attempts": 0}
        checkpoints.append(entry)
    entry["passed"] = entry["passed"] or correct
    entry["attempts"] = int(entry.get("attempts", 0)) + 1
    attempt.checkpoints = checkpoints
    attempt.last_activity_at = datetime.now(timezone.utc)

    questions = await _load_questions(db, attempt.module_id)
    _progress_into(attempt, questions)

    db.add(PlaybackEvent(
        attempt_id=attempt.id,
        event_type="checkpoint",
        position=payload.get("position", 0.0),
        event_data={"question_id": str(question.id), "correct": correct},
    ))
    await db.commit()

    return {
        "ok": True,
        "correct": correct,
        "passed": entry["passed"],
        "status": attempt.status.value,
        "explanation": question.explanation,
        "explanation_ne": question.explanation_ne,
        "checkpoints": [
            {"question_id": str(c["question_id"]), "passed": c["passed"], "attempts": c.get("attempts", 0)}
            for c in attempt.checkpoints
        ],
    }


@router.post("/training/quiz")
async def training_quiz(payload: dict, db: AsyncSession = Depends(get_public_db)):
    attempt = await _get_attempt(db, payload.get("attempt_id"))
    if attempt is None:
        return {"ok": False, "error": "Attempt not found"}
    if not _session_ok(attempt, str(payload.get("session") or ""), datetime.now(timezone.utc)):
        return {"ok": False, "code": "inactive_session", "message": "This lesson is playing in another window."}

    questions = await _load_questions(db, attempt.module_id)
    quiz_questions = [q for q in questions if q.checkpoint_after_seconds is None]
    if not quiz_questions:
        return {"ok": False, "error": "No quiz questions for this lesson"}

    answers = {str(a.get("question_id")): int(a.get("answer_index", -1)) for a in (payload.get("answers") or [])}
    results = []
    correct = 0
    for q in quiz_questions:
        is_correct = answers.get(str(q.id)) == q.correct_index
        correct += int(is_correct)
        results.append({
            "question_id": q.id,
            "correct": is_correct,
            "correct_index": q.correct_index,
            "explanation": q.explanation,
            "explanation_ne": q.explanation_ne,
        })
    score = round(correct / len(quiz_questions) * 100)
    module = await db.get(TrainingModule, attempt.module_id)
    passed = score >= (module.pass_score or 80)

    attempt.quiz_score = score
    attempt.quiz_passed = passed
    attempt.last_activity_at = datetime.now(timezone.utc)

    db.add(PlaybackEvent(
        attempt_id=attempt.id,
        event_type="quiz",
        position=payload.get("position", 0.0),
        event_data={"score": score, "passed": passed},
    ))
    await db.commit()

    return {
        "ok": True,
        "score": score,
        "passed": passed,
        "required": module.pass_score or 80,
        "status": attempt.status.value,
        "results": results,
    }


@router.post("/training/complete")
async def training_complete(payload: dict, db: AsyncSession = Depends(get_public_db)):
    attempt = await _get_attempt(db, payload.get("attempt_id"))
    if attempt is None:
        return {"ok": False, "error": "Attempt not found"}
    if not _session_ok(attempt, str(payload.get("session") or ""), datetime.now(timezone.utc)):
        return {"ok": False, "code": "inactive_session", "message": "This lesson is playing in another window."}

    module = await db.get(TrainingModule, attempt.module_id)
    questions = await _load_questions(db, attempt.module_id)
    quiz_questions = [q for q in questions if q.checkpoint_after_seconds is None]
    checkpoint_questions = [q for q in questions if q.checkpoint_after_seconds is not None]
    done = {str(c["question_id"]) for c in (attempt.checkpoints or []) if c.get("passed")}
    checkpoint_ids = {str(q.id) for q in checkpoint_questions}

    missing = []
    if attempt.completion_percentage < COMPLETION_COVERAGE * 100:
        missing.append("video")
    if checkpoint_ids and not checkpoint_ids.issubset(done):
        missing.append("checkpoints")
    if quiz_questions and not attempt.quiz_passed:
        missing.append("quiz")

    now = datetime.now(timezone.utc)
    if missing:
        attempt.last_activity_at = now
        await db.commit()
        return {
            "ok": True, "completed": False, "missing": missing,
            "status": attempt.status.value,
            "completion_percentage": attempt.completion_percentage,
            "quiz_score": attempt.quiz_score,
        }

    attempt.status = TrainingStatus.COMPLETED
    attempt.completed_at = now
    attempt.last_activity_at = now
    await db.commit()

    # Mark the campaign result trained so org reporting reflects it.
    if attempt.result_id:
        result = await db.get(CampaignResult, attempt.result_id)
        if result is not None:
            result.training_completed = True
            result.training_completed_at = now
            db.add(PhishingEvent(
                org_id=attempt.org_id,
                campaign_id=attempt.campaign_id or result.campaign_id,
                result_id=result.id,
                event_type=EventType.TRAINING_COMPLETED,
            ))
            await db.commit()
            from .remediation import complete_remediation  # local import avoids a cycle

            await complete_remediation(db, result)

    return {
        "ok": True,
        "completed": True,
        "status": attempt.status.value,
        "completion_percentage": attempt.completion_percentage,
        "verified_watch_seconds": round(_union_length(attempt.watch_segments or []), 1),
        "checkpoints_passed": len(done),
        "checkpoints_total": len(checkpoint_ids),
        "quiz_score": attempt.quiz_score,
        "invalid_flags": attempt.invalid_flags or [],
        "completed_at": now,
    }


# ── Seed lessons (global library, bilingual) ────────────────────────────────

def _module_spec(title, title_ne, description, description_ne, failure_type, key_points_en, key_points_ne, questions):
    return {
        "title": title, "title_ne": title_ne,
        "description": description, "description_ne": description_ne,
        "failure_type": failure_type,
        "key_points_en": key_points_en, "key_points_ne": key_points_ne,
        "questions": questions,
    }


def _q(prompt, prompt_ne, options, correct_index, checkpoint_after_seconds, explanation, explanation_ne):
    return {
        "prompt": prompt, "prompt_ne": prompt_ne, "options": options,
        "correct_index": correct_index, "checkpoint_after_seconds": checkpoint_after_seconds,
        "explanation": explanation, "explanation_ne": explanation_ne,
    }


SEED_MODULES = [
    _module_spec(
        "Phishing Basics: Spot the Hook",
        "फिशिङका आधारभूत कुरा: हुक चिन्नुहोस्",
        "Learn the four universal red flags of phishing emails and the safe habits that protect you.",
        "फिशिङ इमेलका चार सामान्य संकेत र सुरक्षित बानीहरूबारे जान्नुहोस्।",
        "phishing-basics",
        [
            "Sender: verify the exact email address, not just the display name.",
            "Urgency is a weapon — pressure is designed to stop you thinking.",
            "Hover every link before you click and check the real domain.",
            "Real companies never ask for your password by email.",
        ],
        [
            "पठाउनेको सही इमेल ठेगाना जाँच्नुहोस्, प्रदर्शन नाम होइन।",
            "हतारो एउटा हतियार हो — दबाबले तपाईंलाई सोच्नबाट रोक्न डिजाइन गरिएको हुन्छ।",
            "क्लिक गर्नुअघि हरेक लिङ्कमा hover गरी वास्तविक डोमेन हेर्नुहोस्।",
            "वास्तविक कम्पनीहरूले इमेलबाट कहिल्यै पासवर्ड माग्दैनन्।",
        ],
        [
            _q(
                "What is the FIRST thing to verify about an email?",
                "इमेलबारे सबैभन्दा पहिले के जाँच्नुपर्छ?",
                ["The sender's display name", "The exact sender email address", "How long the email is", "The company logo"],
                1, 40,
                "The display name can be faked ('IT Support'); the exact email address cannot be trusted until you verify its domain.",
                "प्रदर्शन नाम नक्कली हुन सक्छ ('IT Support'); सही इमेल ठेगानाको डोमेन जाँचेपछि मात्र विश्वास गर्नुहोस्।",
            ),
            _q(
                "Why do phishers create a sense of urgency?",
                "फिशरहरूले हतारोको भावना किन सिर्जना गर्छन्?",
                ["To seem polite", "To rush you past careful thinking", "To make the email shorter", "To avoid spam filters"],
                1, 85,
                "Pressure short-circuits caution. Pause, breathe, and inspect before acting.",
                "दबाबले सतर्कतालाई छोटो पार्छ। रोकिनुहोस्, गहिरो सास लिनुहोस् र कार्य गर्नुअघि जाँच्नुहोस्।",
            ),
            _q(
                "A bank email asks you to 'verify your account immediately' with a login link. What should you do?",
                "एउटा बैंक इमेलले 'तुरुन्त आफ्नो खाता प्रमाणित गर्नुहोस्' भनी लगइन लिङ्क पठाउँछ। के गर्नुपर्छ?",
                ["Click the link and log in", "Reply to ask if it's real", "Open your browser, type the bank's website yourself, and log in there", "Forward it to a friend"],
                2, None,
                "Never follow login links from email. Navigate to the site yourself — a phish always disappears on the real site.",
                "इमेलबाट आएका लगइन लिङ्क पछ्याउनु हुँदैन। आफैं ब्राउजर खोलेर बैंकको असली वेबसाइटमा जानुहोस् — फिश वास्तविक साइटमा गायब हुन्छ।",
            ),
            _q(
                "Which of these is a sign of a phishing email?",
                "यीमध्ये कुन फिशिङ इमेलको संकेत हो?",
                ["A greeting using your first name", "An unexpected request plus a mismatched link domain", "A short subject line", "A message from a colleague you know"],
                1, None,
                "The combination of 'unexpected' + 'link that doesn't match the claimed sender' is a classic phish.",
                "'अप्रत्याशित' + 'दाबी गरिएको पठाउनेसँग नमिल्ने लिङ्क डोमेन' को संयोजन क्लासिक फिश हो।",
            ),
            _q(
                "If you already clicked a suspicious link, the best next step is:",
                "यदि तपाईंले शंकास्पद लिङ्कमा क्लिक गरिसक्नुभयो भने सबैभन्दा राम्रो अर्को कदम हो:",
                ["Do nothing — it's probably fine", "Keep it private so no one knows", "Report it to your security team immediately", "Click it again to check"],
                2, None,
                "Reporting after a click is never penalized — it's exactly the behavior security teams reward.",
                "क्लिकपछि रिपोर्ट गर्नु कहिल्यै दण्ड होइन — सुरक्षा टोलीहरूले यही व्यवहार पुरस्कृत गर्छन्।",
            ),
        ],
    ),
    _module_spec(
        "Credential Phishing: Protect Your Password",
        "क्रेडेन्सियल फिशिङ: आफ्नो पासवर्ड जोगाउनुहोस्",
        "Why fake login pages exist, how to recognize them, and how to keep your credentials safe.",
        "नक्कली लगइन पेज किन हुन्छ, तिनलाई कसरी चिन्ने, र पासवर्ड कसरी सुरक्षित राख्ने।",
        "credential-phishing",
        [
            "A login page is only safe if you reached it by typing the address yourself.",
            "The address bar is the first place to look — check the domain letter by letter.",
            "Never reuse passwords; a stolen one should only break one account.",
            "Enable MFA so a stolen password is not enough.",
        ],
        [
            "लगइन पेज सुरक्षित हुन्छ जब तपाईं आफैंले ठेगाना टाइप गरेर पुग्नुहुन्छ।",
            "ठेगाना पट्टी नै पहिलो हेर्ने ठाउँ हो — डोमेन अक्षरैपिच्छे जाँच्नुहोस्।",
            "पासवर्ड दोहोर्‍याउनु हुँदैन; चोरी भएको पासवर्डले एउटा खाता मात्र तोड्न सक्छ।",
            "MFA सक्रिय गर्नुहोस् ताकि चोरीको पासवर्डले मात्र पर्याप्त नहोस्।",
        ],
        [
            _q(
                "An email says your password expires in 24 hours and asks you to 'keep my password'. What's the risk?",
                "इमेलले २४ घण्टाभित्र पासवर्ड समाप्त हुने र 'पासवर्ड राख्नुहोस्' भनी सोध्छ। जोखिम के हो?",
                ["Your password is too weak", "The link may lead to a fake IT page that steals your password", "Emails about passwords are always scams", "Nothing — IT sent it"],
                1, 40,
                "Fake 'IT' pages collect the password you type. Always reset passwords from the real portal you type into your browser yourself.",
                "नक्कली 'IT' पेजले तपाईंले टाइप गरेको पासवर्ड चोर्छ। सधैं वास्तविक पोर्टलबाट नै पासवर्ड परिवर्तन गर्नुहोस्।",
            ),
            _q(
                "How can you confirm a login page is legitimate?",
                "लगइन पेज वास्तविक हो भनी कसरी पक्का गर्नुहुन्छ?",
                ["It looks professional", "The domain in the address bar exactly matches the company's real site", "It has a lock icon", "It uses the company logo"],
                1, 85,
                "The lock icon and logo can be copied. Only the exact domain is hard to fake — verify it letter by letter.",
                "लक आइकन र लोगो नक्कल गर्न सकिन्छ। केवल सही डोमेन नक्कल गर्न गाह्रो छ — अक्षरैपिच्छे जाँच्नुहोस्।",
            ),
            _q(
                "Why is reusing the same password across sites dangerous?",
                "धेरै साइटमा एउटै पासवर्ड राख्नु किन खतरनाक छ?",
                ["It's hard to remember", "One leaked password can unlock many accounts", "Websites may reject it", "It slows you down"],
                1, None,
                "Breaches happen constantly. A password stolen from one service must not open your bank or email.",
                "ब्रेचहरू निरन्तर हुन्छन्। एउटा सेवाबाट चोरी भएको पासवर्डले बैंक वा इमेल खोल्नु हुँदैन।",
            ),
            _q(
                "You enter your password on a page that looks exactly like your company's portal, but the domain is 'acme-verify.net'. What happened?",
                "कम्पनीको पोर्टलजस्तै देखिने पेजमा पासवर्ड टाइप गर्नुभयो, तर डोमेन 'acme-verify.net' छ। के भयो?",
                ["Nothing — it's a mirror site", "You likely handed your password to attackers", "It's just a test", "The site will redirect you safely"],
                1, None,
                "A lookalike domain means you just typed credentials into an attacker's page. Change the password now and report it.",
                "समान देखिने डोमेनको अर्थ तपाईंले आक्रमणकारीको पेजमा पासवर्ड टाइप गर्नुभयो। अहिले नै पासवर्ड परिवर्तन गरी रिपोर्ट गर्नुहोस्।",
            ),
            _q(
                "What is the strongest single protection against a stolen password?",
                "चोरी भएको पासवर्डविरुद्ध सबैभन्दा बलियो एकल सुरक्षा के हो?",
                ["A longer password", "Multi-factor authentication (MFA)", "Changing it every week", "Memorizing it"],
                1, None,
                "Even with your password, an attacker cannot pass an MFA step they don't control.",
                "पासवर्ड भए पनि, आक्रमणकारीले नियन्त्रण नगर्ने MFA चरण पार गर्न सक्दैन।",
            ),
        ],
    ),
    _module_spec(
        "Malicious Links & Attachments",
        "दुर्भावनापूर्ण लिङ्क र एट्याचमेन्ट",
        "How a single click on a document or meeting link can spread harm — and the habits that stop it.",
        "डकुमेन्ट वा मिटिङ लिङ्कमा एउटा क्लिकले कसरी हानि फैलाउन सक्छ — र यसलाई रोक्ने बानीहरू।",
        "malware-link",
        [
            "Shared-file and calendar invites are favourite disguise for malware links.",
            "Check the real destination by hovering the link before you click.",
            "When in doubt, type the site address yourself or ask the sender by phone.",
            "Don't enable macros or scripts in attachments from email.",
        ],
        [
            "साझा फाइल र क्यालेन्डर निमन्त्रणा मालवेयर लिङ्कको मनपर्ने भेष हो।",
            "क्लिक गर्नुअघि लिङ्कमा hover गरी वास्तविक गन्तव्य जाँच्नुहोस्।",
            "शंका लागे आफैं ठेगाना टाइप गर्नुहोस् वा फोनमा पठाउनेलाई सोध्नुहोस्।",
            "इमेलको एट्याचमेन्टमा म्याक्रो वा स्क्रिप्ट सक्रिय नगर्नुहोस्।",
        ],
        [
            _q(
                "A colleague 'shares a Q3 budget file' with a link. What should you check first?",
                "सहकर्मीले 'Q3 बजेट फाइल' साझा गरेर लिङ्क पठाउँछन्। पहिले के जाँच्नुपर्छ?",
                ["Whether the file name ends in .xlsx", "Whether the link actually goes to the document site, not a lookalike", "Whether the email has a signature", "Nothing — it's from a colleague"],
                1, 40,
                "The file name can be anything; the link's real domain is the truth. Hover before you click.",
                "फाइलको नाम केही पनि हुन सक्छ; लिङ्कको वास्तविक डोमेन नै सत्य हो। क्लिकअघि hover गर्नुहोस्।",
            ),
            _q(
                "A meeting invite says 'the calendar glitched, use this link to join'. Why is that suspicious?",
                "मिटिङ निमन्त्रणा भन्छ 'क्यालेन्डर गडबड भयो, सामेल हुन यो लिङ्क प्रयोग गर्नुहोस्'। यो किन शंकास्पद छ?",
                ["Meeting invites are always safe", "It pushes you to a link outside your normal meeting tool", "It's too short", "It was sent on a weekend"],
                1, 85,
                "Moving you to an unfamiliar link is the tell. Join meetings from your real calendar tool.",
                "अपरिचित लिङ्कतर्फ धकेल्नु नै संकेत हो। आफ्नो वास्तविक क्यालेन्डर टुलबाट मिटिङमा जानुहोस्।",
            ),
            _q(
                "What does hovering over a link reveal?",
                "लिङ्कमा hover गर्दा के थाहा हुन्छ?",
                ["The true URL you would visit", "Whether the email is encrypted", "The sender's phone number", "Nothing at all"],
                0, None,
                "Hovering shows the real destination before any click happens.",
                "Hover गर्दा क्लिक गर्नुअघि नै वास्तविक गन्तव्य देखिन्छ।",
            ),
            _q(
                "An attachment asks you to 'enable macros to view the document'. You should:",
                "एट्याचमेन्टले 'डकुमेन्ट हेर्न म्याक्रो सक्षम गर्नुहोस्' भन्छ। तपाईंले:",
                ["Enable macros — it's required", "Open it in an isolated preview and never enable macros", "Forward it to a friend", "Rename the file and open it"],
                1, None,
                "Enabling macros from email is how malware installs. Preview, don't execute.",
                "इमेलबाट म्याक्रो सक्षम गर्दा मालवेयर स्थापना हुन्छ। प्रिभ्यु गर्नुहोस्, कार्यान्वयन गर्नुहुँदैन।",
            ),
            _q(
                "You clicked a link that downloaded an unexpected file. Best next step?",
                "एउटा लिङ्कमा क्लिक गर्दा अप्रत्याशित फाइल डाउनलोड भयो। सबैभन्दा राम्रो अर्को कदम?",
                ["Open it to see what it is", "Quarantine it and report to security", "Move it to your desktop", "Email it to your manager"],
                1, None,
                "Unexpected downloads should be quarantined and reported — never opened.",
                "अप्रत्याशित डाउनलोड क्वारेन्टाइन गरी रिपोर्ट गर्नुपर्छ — कहिल्यै खोल्नु हुँदैन।",
            ),
        ],
    ),
    _module_spec(
        "Urgency & Bait Tactics",
        "हतारो र प्रलोभनको चाल",
        "How phishers weaponize deadlines, refunds, and 'final notices' to get you to act without thinking.",
        "फिशरहरूले म्याद, रिफन्ड र 'अन्तिम सूचना' लाई कसरी सोचविना कार्य गराउने हतियार बनाउँछन्।",
        "urgency-bait",
        [
            "Legitimate deadlines exist, but real services don't punish you with a single email.",
            "Refunds and prizes you never claimed are bait — verify from the official channel.",
            "Take the pressure off: pause 60 seconds and re-read the email.",
            "Check if you even have an account, parcel, or policy with the sender.",
        ],
        [
            "वास्तविक म्याद हुन्छ, तर वास्तविक सेवाले एउटै इमेलले दण्ड दिँदैन।",
            "दाबी नगरेको रिफन्ड वा पुरस्कार प्रलोभन हो — आधिकारिक माध्यमबाट प्रमाणित गर्नुहोस्।",
            "दबाब हटाउनुहोस्: ६० सेकेन्ड रोकेर इमेल फेरि पढ्नुहोस्।",
            "पठाउनेसँग तपाईंको खाता, पार्सल वा नीति छ कि छैन जाँच्नुहोस्।",
        ],
        [
            _q(
                "A message says your parcel 'will be returned in 48 hours' and to reschedule via a link. First reaction?",
                "सन्देश भन्छ '४८ घण्टामा पार्सल फिर्ता हुनेछ' र लिङ्कबाट पुनः निर्धारण गर्न। पहिलो प्रतिक्रिया?",
                ["Click the link before it's too late", "Check the sender and the link's domain before acting", "Pay the rescheduling fee", "Reply 'stop'"],
                1, 40,
                "Parcel deadlines are a classic panic trigger. Verify you have a parcel with that sender first.",
                "पार्सल म्याद प्यानिक ट्रिगर हो। पहिले पठाउनेसँग पार्सल छ कि छैन जाँच्नुहोस्।",
            ),
            _q(
                "Why do phishers write 'closing soon', 'expires today', 'immediate action'?",
                "फिशरहरूले 'चाँडै बन्द', 'आज समाप्त', 'तत्काल कारबाही' किन लेख्छन्?",
                ["To be helpful", "To make you act before you verify", "Because emails are urgent", "To follow company style"],
                1, 85,
                "Urgency buys compliance. The faster you act, the less likely you are to check.",
                "हतारोले अनुपालन किन्छ। जति छिटो कार्य गर्नुहुन्छ, जाँच्ने सम्भावना त्यति कम हुन्छ।",
            ),
            _q(
                "You get an email about a tax refund you 'never claimed'. The safest response:",
                "'दाबी नगरेको' कर फिर्ताको इमेल आयो। सबैभन्दा सुरक्षित प्रतिक्रिया:",
                ["Claim it immediately", "Contact the official department through the number/portal on their real website", "Send your bank details by email", "Call the number in the email"],
                1, None,
                "Never reply with details or use contact info from the email. Use the official channel's own contact details.",
                "इमेलबाट विवरण पठाउनु वा इमेलको सम्पर्क प्रयोग गर्नु हुँदैन। आधिकारिक माध्यमको सम्पर्क प्रयोग गर्नुहोस्।",
            ),
            _q(
                "A 'final notice' threatens account closure today unless you sign in. What's most likely true?",
                "'अन्तिम सूचना' ले आज खाता बन्द हुने धम्की दिन्छ। के सबैभन्दा सत्य हो?",
                ["Your account really closes today", "It's a pressure tactic to collect your credentials", "The company is cancelling accounts", "You must act now"],
                1, None,
                "Threats of instant closure are almost always pressure tactics, not policy.",
                "तुरुन्त बन्दको धम्की प्रायः नीति होइन, दबाबको चाल हुन्छ।",
            ),
            _q(
                "The single best habit when an email pressures you:",
                "इमेलले दबाब दिँदा सबैभन्दा राम्रो बानी:",
                ["Act within 10 seconds", "Pause, verify the sender and links, then act calmly", "Forward to your team quickly", "Delete and ignore forever"],
                1, None,
                "Pausing converts a potential victim into a careful reviewer.",
                "रोकिनुले सम्भावित पीडितलाई सतर्क समीक्षक बनाउँछ।",
            ),
        ],
    ),
]


async def seed_training_modules(db: AsyncSession) -> None:
    """Idempotent seed of the global lesson library. Only runs when no global
    module exists yet, so tenant edits and future versions are preserved."""
    existing = (await db.execute(
        select(TrainingModule).where(TrainingModule.org_id.is_(None)).limit(1)
    )).scalars().first()
    if existing is None:
        for index, spec in enumerate(SEED_MODULES):
            module = TrainingModule(
                org_id=None,
                title=spec["title"],
                title_ne=spec["title_ne"],
                description=spec["description"],
                description_ne=spec["description_ne"],
                failure_type=spec["failure_type"],
                video_url_en=_media_url(spec["failure_type"], "en"),
                video_url_ne=_media_url(spec["failure_type"], "ne"),
                audio_url_en=None,
                audio_url_ne=None,
                duration_seconds=lesson_duration_seconds(spec["failure_type"], "en"),
                pass_score=80,
                key_points_en=spec["key_points_en"],
                key_points_ne=spec["key_points_ne"],
                is_active=True,
                version=1,
            )
            db.add(module)
            await db.flush()
            for q in spec["questions"]:
                db.add(TrainingQuestion(
                    module_id=module.id,
                    prompt=q["prompt"],
                    prompt_ne=q["prompt_ne"],
                    options=q["options"],
                    correct_index=q["correct_index"],
                    checkpoint_after_seconds=q["checkpoint_after_seconds"],
                    explanation=q["explanation"],
                    explanation_ne=q["explanation_ne"],
                ))
    await _refresh_seeded_videos(db)
    await db.commit()


async def _refresh_seeded_videos(db: AsyncSession) -> None:
    """Swap any global module still on a legacy/off-topic media URL onto its
    topic-specific training video, and enforce the minimum lesson length."""
    modules = (
        await db.execute(select(TrainingModule).where(TrainingModule.org_id.is_(None)))
    ).scalars().all()
    changed = False
    for module in modules:
        if module.video_url_en in LEGACY_VIDEO_URLS or not module.video_url_en:
            module.video_url_en = _media_url(module.failure_type or "phishing-basics", "en")
            changed = True
        elif not str(module.video_url_en).startswith(MEDIA_BASE):
            module.video_url_en = _media_url(module.failure_type or "phishing-basics", "en")
            changed = True
        if module.video_url_ne in LEGACY_VIDEO_URLS or not module.video_url_ne:
            module.video_url_ne = _media_url(module.failure_type or "phishing-basics", "ne")
            changed = True
        elif not str(module.video_url_ne).startswith(MEDIA_BASE):
            module.video_url_ne = _media_url(module.failure_type or "phishing-basics", "ne")
            changed = True
        expected = lesson_duration_seconds(module.failure_type or "phishing-basics", "en")
        if abs((module.duration_seconds or 0) - expected) > 2:
            module.duration_seconds = expected
            changed = True
    if changed:
        await db.flush()
